import type { Metadata } from "next";
import { Urbanist } from 'next/font/google'
import { Theme } from '@radix-ui/themes';
import "./globals.css";

const urbanist = Urbanist({ subsets: ['latin'], variable: '--font-urbanist' })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className={urbanist.variable} lang="en">
      <body className="bg-zinc-50 antialiased">
        <Theme>
          {children}
        </Theme>
      </body>
    </html>
  );
}
