export const locations = [
    { value: 'porto-alegre', label: 'Porto Alegre' },
    { value: 'caminho-das-arvores', label: 'Caminho das Árvores' },
    { value: 'centro-historico', label: 'Centro Histórico' },
    { value: 'bela-vista', label: 'Bela Vista' },
    { value: 'moinhos-de-vento', label: 'Moinhos de Vento' },
    { value: 'cidade-baixa', label: 'Cidade Baixa' },
    { value: 'sao-joao', label: 'São João' },
    { value: 'humaita', label: 'Humaitá' },
    { value: 'menino-deus', label: 'Menino Deus' },
    { value: 'jardim-botanico', label: 'Jardim Botânico' },
    { value: 'sarandi', label: 'Sarandi' },
    { value: 'santa-maria', label: 'Santa Maria' },
    { value: 'vila-joao', label: 'Vila João' },
    { value: 'bom-fim', label: 'Bom Fim' },
    { value: 'cristal', label: 'Cristal' },
    { value: 'camaquã', label: 'Camaquã' },
    { value: 'guarani', label: 'Guarani' },
    { value: 'partenon', label: 'Partenon' },
    { value: 'ilha-das-pedras', label: 'Ilha das Pedras' },
    { value: 'santo-antonio', label: 'Santo Antônio' },
    { value: 'tristeza', label: 'Tristeza' },
    { value: 'vila-izabel', label: 'Vila Izabel' },
];
